pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                   sudo yum install nodejs nodejs-devel -y
                   ls -la
                   node --version
                   npm --version
                   npm ci
                   npm run build
                   ls -la
                '''
            }
        }
    }
}
